export type BlogBlock =
  | { type: "heading"; text: string }
  | { type: "paragraph"; text: string }
  | { type: "list"; items: string[] };

export interface Blog {
  slug: string;
  title: string;
  tags: string[];
  image: string;
  author?: string;
  createdAt?: string;
  content?: BlogBlock[];
  relatedSlugs?: string[];
}

export const blogs: Blog[] = [
  {
    slug: "what-is-an-explainer-video",
    title: "What is an Explainer Video? Benefits and Uses Explained ",
    tags: ["beauty", "products", "video"],
    image: "/blogs/blog-01.webp",
    author: "Pocket Creatives",
    createdAt: "28th February 2022",
    content: [],
    relatedSlugs: [],
  },
  {
    slug: "beauty-product-photography-pony-revolution",
    title: "Beauty Product Photography for Pony Revolution",
    tags: ["beauty", "photography", "products", "video"],
    image: "/blogs/blog-02.webp",
    author: "Pocket Creatives",
    createdAt: "14th March 2022",
    content: [],
    relatedSlugs: [],
  },
  {
    slug: "meeting-gouri-kubair-at-holy-lama",
    title: "Meeting Gouri Kubair at Holy Lama",
    tags: ["beauty"],
    image: "/blogs/blog-03.webp",
    author: "Pocket Creatives",
    createdAt: "3rd January 2022",
    content: [],
    relatedSlugs: [],
  },
  {
    slug: "shooting-stop-motion-video",
    title: "Shooting Stop Motion Video",
    tags: ["beauty", "video"],
    image: "/blogs/blog-04.webp",
    author: "Pocket Creatives",
    createdAt: "21st November 2021",
    content: [],
    relatedSlugs: [],
  },
  {
    slug: "christmas-photography-2020",
    title: "Christmas Photography 2020",
    tags: ["photography", "beauty", "jewellery", "products"],
    image: "/blogs/blog-05.webp",
    author: "Pocket Creatives",
    createdAt: "25th December 2020",
    content: [],
    relatedSlugs: [],
  },
  {
    slug: "6-beauty-photography-tips",
    title: "6 Beauty Photography Tips",
    tags: ["beauty"],
    image: "/blogs/blog-06.webp",
    author: "Pocket Creatives",
    createdAt: "9th August 2021",
    content: [],
    relatedSlugs: [],
  },
  {
    slug: "model-behaviour",
    title: "Model Behaviour",
    tags: ["beauty", "people", "photography", "portraits"],
    image: "/blogs/blog-07.webp",
    author: "Pocket Creatives",
    createdAt: "17th June 2021",
    content: [],
    relatedSlugs: [],
  },
  {
    slug: "created-at-home",
    title: "Created at home",
    tags: ["photography", "beauty", "food", "food & drink", "products"],
    image: "/blogs/blog-08.webp",
    author: "Pocket Creatives",
    createdAt: "2nd May 2021",
    content: [],
    relatedSlugs: [],
  },
  {
    slug: "christmas-photography-content",
    title: "Christmas Photography Content",
    tags: ["photography", "beauty", "food", "food & drink", "watches"],
    image: "/blogs/blog-09.webp",
    author: "Pocket Creatives",
    createdAt: "22nd December 2020",
    content: [],
    relatedSlugs: [],
  },
  {
    slug: "fantastic-flat-lay",
    title: "Fantastic Flat Lay",
    tags: ["photography", "beauty", "food", "food & drink"],
    image: "/blogs/blog-10.webp",
    author: "Pocket Creatives",
    createdAt: "11th September 2021",
    content: [],
    relatedSlugs: [],
  },
  {
    slug: "getting-our-nails-into-beauty",
    title: "Getting our nails into beauty",
    tags: ["beauty", "video"],
    image: "/blogs/blog-11.webp",
    author: "Pocket Creatives",
    createdAt: "6th July 2021",
    content: [],
    relatedSlugs: [],
  },
  {
    slug: "scrubs-up-well",
    title: "Scrubs Up Well",
    tags: ["crowdfunding", "beauty", "video"],
    image: "/blogs/blog-12.webp",
    author: "Pocket Creatives",
    createdAt: "30th April 2021",
    content: [],
    relatedSlugs: [],
  },
  {
    slug: "what-is-a-treatment-in-video-production",
    title: "What is a Treatment in Video Production? Expert Answers!",
    tags: ["video"],
    image: "/blogs/blog-13.webp",
    author: "Pocket Creatives",
    createdAt: "20th March 2025",
    relatedSlugs: [
      "what-is-dp-in-video-production",
      "what-are-the-5-stages-of-video-production",
      "crowdfunding-video-for-synergised-uk",
      "beauty-product-photography-pony-revolution",
      "our-product-videographers-shoot-with-skinny-tan",
      "video-production-for-publishing",
      "photography-and-video-production-with-energy",
      "our-first-tv-ad-as-a-video-production-company",
    ],
    content: [
      {
        type: "paragraph",
        text: "Ever had a brilliant video idea but struggled to communicate it clearly? Whether you're planning a product video, brand film, or social media advert, ensuring everyone shares the same vision is crucial. That's where a treatment comes in.",
      },
      {
        type: "paragraph",
        text: "A video treatment is a concise, structured document outlining your video's concept, tone, narrative, and stylistic approach. It acts as a roadmap before scriptwriting, helping directors, clients, and production teams stay aligned.",
      },
      {
        type: "paragraph",
        text: "A well-structured video treatment ensures clarity, minimises revisions, and keeps your creative vision intact. In this guide, we'll break down everything you need to know — from step-by-step structuring to common mistakes to avoid.",
      },
      { type: "heading", text: "What is a Treatment in Video Production?" },
      {
        type: "paragraph",
        text: "A video treatment is a pre-production document that summarises a project's creative vision, story structure, and stylistic approach. It's often used before scriptwriting to define the mood, tone, and key messaging of the video.",
      },
      { type: "paragraph", text: "A treatment is particularly useful for:" },
      {
        type: "list",
        items: [
          "Aligning stakeholders — ensuring everyone shares the same creative vision.",
          "Pitching ideas — helping clients, investors, or internal teams approve a concept.",
          "Minimising revisions — reducing confusion and costly reshoots during production.",
        ],
      },
      {
        type: "heading",
        text: "Treatment vs. Script vs. Storyboard — What's the Difference?",
      },
      {
        type: "paragraph",
        text: "A treatment covers high-level concept and visual style, focused on big-picture storytelling. A script covers detailed dialogue and scene actions, tracking every word and movement. A storyboard covers shot-by-shot visual representation, mapping camera angles and flow.",
      },
      {
        type: "paragraph",
        text: "If you're wondering what a treatment in video production is, it's essentially the first step to transforming an idea into a fully structured video concept.",
      },
      {
        type: "heading",
        text: "Different Types of Video Treatments & Their Use-Cases",
      },
      {
        type: "paragraph",
        text: "Not all video treatments are created equal! Depending on the type of video, a treatment can vary significantly in structure, tone, and purpose. Here's how treatments differ based on video type:",
      },
      {
        type: "paragraph",
        text: "Commercial Video Treatment — used by brands to develop advertising concepts before production, focusing on storytelling, emotional triggers, and brand messaging. Often includes a mood board, visual style guide, and proposed call-to-action (CTA).",
      },
      {
        type: "paragraph",
        text: "Corporate Video Treatment — ideal for company overview videos, testimonials, or training content. Emphasises clarity, professionalism, and messaging alignment, often with structured interview segments, voice over scripting, and branding elements.",
      },
      {
        type: "paragraph",
        text: "Product Video Treatment — essential for eCommerce, product showcases, and explainer videos. Focuses on highlighting product features, functionality, and benefits, and may include macro product shots, animation concepts, and demonstration sequences.",
      },
      {
        type: "paragraph",
        text: "Event Video Treatment — guides the filming of conferences, product launches, or live events. Details multi-camera setups, key interview shots, crowd interactions, and event highlights, ensuring smooth coverage with a shot list and schedule.",
      },
      {
        type: "paragraph",
        text: "Social Media Video Treatment — short-form, engaging, and highly visual. Optimised for Instagram Reels, TikTok, and YouTube Shorts, focusing on snappy edits, eye-catching transitions, and mobile-friendly framing.",
      },
      {
        type: "paragraph",
        text: "At Pocket Creatives, we tailor each treatment to match the brand's goals, audience, and video platform — ensuring every project delivers maximum impact. If you're still asking what a treatment in video production is, the answer is it's an essential blueprint for video success.",
      },
      { type: "heading", text: "Why is a Video Treatment Important?" },
      {
        type: "paragraph",
        text: "A video production treatment isn't just a creative exercise — it's a practical tool that saves time, money, and confusion.",
      },
      { type: "paragraph", text: "Key Benefits:" },
      {
        type: "list",
        items: [
          "Clarity & Direction — A well-structured treatment eliminates misinterpretation between teams.",
          "Client Approvals — Treatments provide a clear preview of the video's message before investing in production.",
          "Fewer Revisions — A solid treatment reduces back-and-forth changes, cutting production delays.",
          "Professionalism — Agencies and brands expect structured treatments before committing to large-scale projects.",
          "Brand Consistency — A well-written treatment not only improves creative alignment but also strengthens brand consistency.",
        ],
      },
      {
        type: "paragraph",
        text: "By outlining visual and messaging guidelines upfront, businesses can ensure that every video reflects their brand identity. This makes marketing efforts more cohesive across different campaigns, improving audience trust and recognition.",
      },
      {
        type: "paragraph",
        text: "For example, at Pocket Creatives, when working on a crowdfunding video for a beauty brand, a treatment helped refine the product's visual story before production, avoiding costly mid-project changes.",
      },
    ],
  },
  {
    slug: "what-is-dp-in-video-production",
    title: "What is DP in Video Production? Role & Importance Explained",
    tags: ["video", "company"],
    image: "/blogs/blog-14.webp",
    author: "Pocket Creatives",
    createdAt: "12th January 2023",
    content: [],
    relatedSlugs: [],
  },
  {
    slug: "what-are-the-5-stages-of-video-production",
    title: "What Are The 5 Stages of Video Production? (Essential Guide)",
    tags: ["video", "company"],
    image: "/blogs/blog-15.webp",
    author: "Pocket Creatives",
    createdAt: "3rd February 2023",
    content: [],
    relatedSlugs: [],
  },
  {
    slug: "crowdfunding-video-for-synergised-uk",
    title: "Crowdfunding video for Synergised UK",
    tags: ["crowdfunding", "video"],
    image: "/blogs/blog-16.webp",
    author: "Paula",
    createdAt: "18th April 2023",
    content: [],
    relatedSlugs: [],
  },
  {
    slug: "our-product-videographers-shoot-with-skinny-tan",
    title: "Our Product Videographers Shoot With Skinny Tan",
    tags: ["beauty", "products", "video"],
    image: "/blogs/blog-01.webp",
    author: "Pocket Creatives",
    createdAt: "9th May 2023",
    content: [],
    relatedSlugs: [],
  },
  {
    slug: "video-production-for-publishing",
    title: "Video Production For Publishing",
    tags: ["video", "company"],
    image: "/blogs/blog-18.webp",
    author: "Ian Sanders",
    createdAt: "27th June 2023",
    content: [],
    relatedSlugs: [],
  },
  {
    slug: "photography-and-video-production-with-energy",
    title: "Photography and video production with energy",
    tags: ["photography", "video"],
    image: "/blogs/blog-19.webp",
    author: "Pocket Creatives",
    createdAt: "14th August 2023",
    content: [],
    relatedSlugs: [],
  },
  {
    slug: "our-first-tv-ad-as-a-video-production-company",
    title: "Our first TV ad as a Video Production Company",
    tags: ["video", "company"],
    image: "/blogs/blog-20.webp",
    author: "Pocket Creatives",
    createdAt: "2nd October 2023",
    content: [],
    relatedSlugs: [],
  },
];

export const blogsPagination = {
  headline: "Our Blogs",
  filters: [
    "Beauty",
    "Company",
    "Crowfunding",
    "Events",
    "Fashion",
    "Food",
    "Food & Drink",
    "Jewellery",
    "People",
    "Photography",
    "Portaits",
    "Products",
    "Video",
  ],
};
